absl-py==1.4.0
alabaster==0.7.8
appdirs==1.4.3
apturl==0.5.2
astunparse==1.6.3
atomicwrites==1.1.5
attrs==19.3.0
Babel==2.6.0
backcall==0.1.0
bcrypt==3.1.7
beautifulsoup4==4.8.2
billiard==4.1.0
blinker==1.4
breezy==3.0.2
Brlapi==0.7.0
cachetools==5.3.1
catkin-pkg==1.0.0
catkin-pkg-modules==1.0.0
catkin-tools==0.9.2
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloudpickle==2.2.1
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
contourpy==1.1.0
cryptography==2.8
cupshelpers==1.0
cycler==0.11.0
dbus-python==1.2.16
decorator==4.4.2
defer==1.0.6
defusedxml==0.6.0
Deprecated==1.2.7
distlib==0.3.0
distro==1.4.0
distro-info==0.23+ubuntu1.1
docopt==0.6.2
docutils==0.16
dulwich==0.19.15
duplicity==0.8.12.0
empy==3.3.2
entrypoints==0.3
fasteners==0.14.1
fastimport==0.9.8
feedparser==5.2.1
filelock==3.0.12
flatbuffers==23.5.26
fonttools==4.42.1
future==0.18.3
gast==0.4.0
gcovr==4.2
genmsg==0.5.14
genpy==0.6.9
gitsome==0.8.0
gnureadline==8.1.2
google-auth==2.22.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
gpg==1.13.1
grpcio==1.57.0
gym==0.11.0
h5py==3.9.0
html5lib==1.0.1
httplib2==0.14.0
idna==2.8
imagesize==1.2.0
importlib-metadata==6.8.0
importlib-resources==6.0.1
ipython==7.13.0
ipython-genutils==0.2.0
jedi==0.15.2
Jinja2==2.10.1
joblib==1.3.2
keras==2.13.1
keyboard==0.13.5
keyring==18.0.1
kiwisolver==1.4.5
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
libclang==16.0.6
lockfile==0.12.2
louis==3.12.0
lxml==4.9.3
macaroonbakery==1.3.1
Mako==1.1.0
Markdown==3.4.4
MarkupSafe==2.1.3
matplotlib==3.7.2
MAVProxy==1.8.67
monotonic==1.5
more-itertools==4.2.0
netifaces==0.10.4
nose==1.3.7
notify2==0.3
numpy==1.24.3
numpydoc==0.7.0
oauthlib==3.1.0
olefile==0.46
opencv-python==4.8.0.76
opt-einsum==3.3.0
osrf-pycommon==2.0.2
packaging==20.3
pandas==2.0.3
paramiko==2.6.0
parso==0.5.2
pexpect==4.6.0
pickleshare==0.7.5
Pillow==7.0.0
Pivy==0.6.5
pluggy==0.13.0
ply==3.11
prompt-toolkit==2.0.10
protobuf==4.24.2
psutil==5.5.1
py==1.8.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pybind11==2.4.3
pybullet==3.2.5
pycairo==1.16.2
pycrypto==2.6.1
pycryptodomex==3.6.1
pycups==1.9.73
pygame==1.9.6
PyGithub==1.43.7
pyglet==2.0.9
Pygments==2.3.1
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
pymavlink==2.4.40
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.6
PyQt5==5.14.1
pyRFC3339==1.1
pyserial==3.4
pytest==4.6.9
python-apt==2.0.1+ubuntu0.20.4.1
python-dateutil==2.8.2
python-debian==0.1.36+ubuntu1.1
python-gitlab==2.0.1
python-gnupg==0.4.5
pytz==2023.3
pyxdg==0.26
PyYAML==5.3.1
reportlab==3.5.34
requests==2.22.0
requests-oauthlib==1.3.1
requests-unixsocket==0.2.0
roman==2.0.0
rosdep==0.22.2
rosdep-modules==0.22.2
rosdistro==0.9.0
rosdistro-modules==0.9.0
rosinstall==0.7.8
rosinstall-generator==0.1.23
rospkg==1.5.0
rospkg-modules==1.5.0
rsa==4.9
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
scipy==1.10.1
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
setproctitle==1.1.10
simplejson==3.16.0
sip==4.19.21
six==1.14.0
soupsieve==1.9.5
Sphinx==1.8.5
ssh-import-id==5.10
stable-baselines==2.10.1
system-service==0.3
systemd-python==234
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorflow==2.13.0
tensorflow-estimator==2.13.0
tensorflow-io-gcs-filesystem==0.33.0
termcolor==2.3.0
traitlets==4.3.3
typing-extensions==4.5.0
tzdata==2023.3
ubuntu-drivers-common==0.0.0
ubuntu-pro-client==8001
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.7
vcstool==0.3.0
vcstools==0.1.42
virtualenv==20.0.17
wadllib==1.3.3
wcwidth==0.1.8
webencodings==0.5.1
werkzeug==2.3.7
wrapt==1.11.2
wstool==0.1.18
wxPython==4.0.7
xkit==0.0.0
xonsh==0.9.13
zipp==3.16.2
